/*
 * Raven API
 * This is OpenAPI defintion for the APIs of Raven.  You can find out more about Raven at [https://ravenapp.dev/](https://ravenapp.dev/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@ravenapp.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

import { RavenApiClient } from "../RavenApiClient";
import {
  convertToType,
  constructFromObject,
  parseDate,
  deserialize,
  buildUrl,
  normalizeParams,
  isFileParam,
  paramToString,
  isJsonMime,
  jsonPreferredMime,
} from "../utils";
export class Attachments {
  constructor() {}

  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Attachments();
      if (data.hasOwnProperty("filename"))
        obj.filename = convertToType(data["filename"], "String");
      if (data.hasOwnProperty("content"))
        obj.content = convertToType(data["content"], "String");
      if (data.hasOwnProperty("url"))
        obj.url = convertToType(data["url"], "String");
    }
    return obj;
  }

  getFilename() {
    return this.filename;
  }

  setFilename(filename) {
    this.filename = filename;
  }

  getContent() {
    return this.content;
  }

  setContent(content) {
    this.content = content;
  }

  getUrl() {
    return this.url;
  }

  setUrl(url) {
    this.url = url;
  }
}

Attachments.prototype.filename = undefined;

Attachments.prototype.content = undefined;

Attachments.prototype.url = undefined;
