/*
 * Raven API
 * This is OpenAPI defintion for the APIs of Raven.  You can find out more about Raven at [https://ravenapp.dev/](https://ravenapp.dev/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@ravenapp.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

import { RavenApiClient } from "../RavenApiClient";
import { Attachments } from "./Attachments";
import { EmailRecipient } from "./EmailRecipient";

export class EmailOverride {
  constructor() {}

  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EmailOverride();
      if (data.hasOwnProperty("from"))
        obj.from = EmailRecipient.constructFromObject(data["from"]);
      if (data.hasOwnProperty("cc"))
        obj.cc = RavenApiClient.convertToType(data["cc"], [EmailRecipient]);
      if (data.hasOwnProperty("bcc"))
        obj.bcc = RavenApiClient.convertToType(data["bcc"], [EmailRecipient]);
      if (data.hasOwnProperty("attachments"))
        obj.attachments = Attachments.constructFromObject(data["attachments"]);
      if (data.hasOwnProperty("scheduled_at"))
        obj.scheduledAt = RavenApiClient.convertToType(
          data["scheduled_at"],
          "String"
        );
    }
    return obj;
  }

  getFrom() {
    return this.from;
  }

  setFrom(from) {
    this.from = from;
  }

  getCc() {
    return this.cc;
  }

  setCc(cc) {
    this.cc = cc;
  }

  getBcc() {
    return this.bcc;
  }

  setBcc(bcc) {
    this.bcc = bcc;
  }

  getAttachments() {
    return this.attachments;
  }

  setAttachments(attachments) {
    this.attachments = attachments;
  }

  getScheduledAt() {
    return this.scheduledAt;
  }

  setScheduledAt(scheduledAt) {
    this.scheduledAt = scheduledAt;
  }
}

EmailOverride.prototype.from = undefined;

EmailOverride.prototype.cc = undefined;

EmailOverride.prototype.bcc = undefined;

EmailOverride.prototype.attachments = undefined;

EmailOverride.prototype.scheduledAt = undefined;
