/*
 * Raven API
 * This is OpenAPI defintion for the APIs of Raven.  You can find out more about Raven at [https://ravenapp.dev/](https://ravenapp.dev/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@ravenapp.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Attachments', 'model/EmailRecipient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Attachments'), require('./EmailRecipient'));
  } else {
    // Browser globals (root is window)
    if (!root.RavenApi) {
      root.RavenApi = {};
    }
    root.RavenApi.EmailOverride = factory(root.RavenApi.ApiClient, root.RavenApi.Attachments, root.RavenApi.EmailRecipient);
  }
}(this, function(ApiClient, Attachments, EmailRecipient) {
  'use strict';

  /**
   * The EmailOverride model module.
   * @module model/EmailOverride
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>EmailOverride</code>.
   * @alias module:model/EmailOverride
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>EmailOverride</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EmailOverride} obj Optional instance to populate.
   * @return {module:model/EmailOverride} The populated <code>EmailOverride</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('from'))
        obj.from = EmailRecipient.constructFromObject(data['from']);
      if (data.hasOwnProperty('cc'))
        obj.cc = ApiClient.convertToType(data['cc'], [EmailRecipient]);
      if (data.hasOwnProperty('bcc'))
        obj.bcc = ApiClient.convertToType(data['bcc'], [EmailRecipient]);
      if (data.hasOwnProperty('attachments'))
        obj.attachments = Attachments.constructFromObject(data['attachments']);
      if (data.hasOwnProperty('scheduled_at'))
        obj.scheduledAt = ApiClient.convertToType(data['scheduled_at'], 'String');
    }
    return obj;
  }

  /**
   * @member {module:model/EmailRecipient} from
   */
  exports.prototype.from = undefined;

  /**
   * @member {Array.<module:model/EmailRecipient>} cc
   */
  exports.prototype.cc = undefined;

  /**
   * @member {Array.<module:model/EmailRecipient>} bcc
   */
  exports.prototype.bcc = undefined;

  /**
   * @member {module:model/Attachments} attachments
   */
  exports.prototype.attachments = undefined;

  /**
   * @member {String} scheduledAt
   */
  exports.prototype.scheduledAt = undefined;


  return exports;

}));
