/*
 * Raven API
 * This is OpenAPI defintion for the APIs of Raven.  You can find out more about Raven at [https://ravenapp.dev/](https://ravenapp.dev/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@ravenapp.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

import { RavenApiClient } from "../RavenApiClient";

export class ErrorResponse {
  constructor() {}

  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ErrorResponse();
      if (data.hasOwnProperty("id"))
        obj.id = RavenApiClient.convertToType(data["id"], "String");
      if (data.hasOwnProperty("error"))
        obj.error = RavenApiClient.convertToType(data["error"], "String");
    }
    return obj;
  }

  getId() {
    return this.id;
  }

  setId(id) {
    this.id = id;
  }

  getError() {
    return this.error;
  }

  setError(error) {
    this.error = error;
  }
}

ErrorResponse.prototype.id = undefined;

ErrorResponse.prototype.error = undefined;
