/*
 * Raven API
 * This is OpenAPI defintion for the APIs of Raven.  You can find out more about Raven at [https://ravenapp.dev/](https://ravenapp.dev/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@ravenapp.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

import { EmailOverride } from "./EmailOverride";
import { ProviderOverride } from "./ProviderOverride";
import { PushOverride } from "./PushOverride";
import { SlackOverride } from "./SlackOverride";
import { SmsOverride } from "./SmsOverride";
import { VoiceOverride } from "./VoiceOverride";
import { WebhookOverride } from "./WebhookOverride";
import { WhatsappOverride } from "./WhatsappOverride";
import { convertToType } from "../utils";
export class EventOverride {
  constructor() {}

  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EventOverride();
      if (data.hasOwnProperty("email"))
        obj.email = EmailOverride.constructFromObject(data["email"]);
      if (data.hasOwnProperty("sms"))
        obj.sms = SmsOverride.constructFromObject(data["sms"]);
      if (data.hasOwnProperty("whatsapp"))
        obj.whatsapp = WhatsappOverride.constructFromObject(data["whatsapp"]);
      if (data.hasOwnProperty("push"))
        obj.push = PushOverride.constructFromObject(data["push"]);
      if (data.hasOwnProperty("webhook"))
        obj.webhook = WebhookOverride.constructFromObject(data["webhook"]);
      if (data.hasOwnProperty("voice"))
        obj.voice = VoiceOverride.constructFromObject(data["voice"]);
      if (data.hasOwnProperty("slack"))
        obj.slack = SlackOverride.constructFromObject(data["slack"]);
      if (data.hasOwnProperty("providers"))
        obj.providers = convertToType(data["providers"], {
          String: ProviderOverride,
        });
    }
    return obj;
  }

  getEmail() {
    return this.email;
  }

  setEmail(email) {
    this.email = email;
  }

  getSms() {
    return this.sms;
  }

  setSms(sms) {
    this.sms = sms;
  }

  getWhatsapp() {
    return this.whatsapp;
  }

  setWhatsapp(whatsapp) {
    this.whatsapp = whatsapp;
  }

  getPush() {
    return this.push;
  }

  setPush(push) {
    this.push = push;
  }

  getWebhook() {
    return this.webhook;
  }

  setWebhook(webhook) {
    this.webhook = webhook;
  }

  getVoice() {
    return this.voice;
  }

  setVoice(voice) {
    this.voice = voice;
  }

  getSlack() {
    return this.slack;
  }

  setSlack(slack) {
    this.slack = slack;
  }

  getProviders() {
    return this.providers;
  }

  setProviders(providers) {
    this.providers = providers;
  }
}

EventOverride.prototype.email = undefined;

EventOverride.prototype.sms = undefined;

EventOverride.prototype.whatsapp = undefined;

EventOverride.prototype.push = undefined;

EventOverride.prototype.webhook = undefined;

EventOverride.prototype.voice = undefined;

EventOverride.prototype.slack = undefined;

EventOverride.prototype.providers = undefined;
