/*
 * Raven API
 * This is OpenAPI defintion for the APIs of Raven.  You can find out more about Raven at [https://ravenapp.dev/](https://ravenapp.dev/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@ravenapp.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

import { RavenApiClient } from "../RavenApiClient";
import { Param } from "./Param";
import { convertToType } from "../utils";
export class ProviderOverride {
  constructor() {}

  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProviderOverride();
      if (data.hasOwnProperty("payload"))
        obj.payload = convertToType(data["payload"], {
          String: Object,
        });
      if (data.hasOwnProperty("form_params"))
        obj.formParams = convertToType(data["form_params"], [Param]);
      if (data.hasOwnProperty("query_params"))
        obj.queryParams = convertToType(data["query_params"], [Param]);
      if (data.hasOwnProperty("config"))
        obj.config = convertToType(data["config"], {
          String: "String",
        });
    }
    return obj;
  }

  getPayload() {
    return this.payload;
  }

  setPayload(payload) {
    this.payload = payload;
  }

  getFormParams() {
    return this.formParams;
  }

  setFormParams(formParams) {
    this.formParams = formParams;
  }

  getQueryParams() {
    return this.queryParams;
  }

  setQueryParams(queryParams) {
    this.queryParams = queryParams;
  }

  getConfig() {
    return this.config;
  }

  setConfig(config) {
    this.config = config;
  }
}

ProviderOverride.prototype.payload = undefined;

ProviderOverride.prototype.formParams = undefined;

ProviderOverride.prototype.queryParams = undefined;

ProviderOverride.prototype.config = undefined;
