/*
 * Raven API
 * This is OpenAPI defintion for the APIs of Raven.  You can find out more about Raven at [https://ravenapp.dev/](https://ravenapp.dev/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@ravenapp.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Param'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Param'));
  } else {
    // Browser globals (root is window)
    if (!root.RavenApi) {
      root.RavenApi = {};
    }
    root.RavenApi.ProviderOverride = factory(root.RavenApi.ApiClient, root.RavenApi.Param);
  }
}(this, function(ApiClient, Param) {
  'use strict';

  /**
   * The ProviderOverride model module.
   * @module model/ProviderOverride
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ProviderOverride</code>.
   * @alias module:model/ProviderOverride
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ProviderOverride</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProviderOverride} obj Optional instance to populate.
   * @return {module:model/ProviderOverride} The populated <code>ProviderOverride</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('payload'))
        obj.payload = ApiClient.convertToType(data['payload'], {'String': Object});
      if (data.hasOwnProperty('form_params'))
        obj.formParams = ApiClient.convertToType(data['form_params'], [Param]);
      if (data.hasOwnProperty('query_params'))
        obj.queryParams = ApiClient.convertToType(data['query_params'], [Param]);
      if (data.hasOwnProperty('config'))
        obj.config = ApiClient.convertToType(data['config'], {'String': 'String'});
    }
    return obj;
  }

  /**
   * @member {Object.<String, Object>} payload
   */
  exports.prototype.payload = undefined;

  /**
   * @member {Array.<module:model/Param>} formParams
   */
  exports.prototype.formParams = undefined;

  /**
   * @member {Array.<module:model/Param>} queryParams
   */
  exports.prototype.queryParams = undefined;

  /**
   * @member {Object.<String, String>} config
   */
  exports.prototype.config = undefined;


  return exports;

}));
