/*
 * Raven API
 * This is OpenAPI defintion for the APIs of Raven.  You can find out more about Raven at [https://ravenapp.dev/](https://ravenapp.dev/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@ravenapp.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Data', 'model/EventOverride', 'model/User'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Data'), require('./EventOverride'), require('./User'));
  } else {
    // Browser globals (root is window)
    if (!root.RavenApi) {
      root.RavenApi = {};
    }
    root.RavenApi.SendEvent = factory(root.RavenApi.ApiClient, root.RavenApi.Data, root.RavenApi.EventOverride, root.RavenApi.User);
  }
}(this, function(ApiClient, Data, EventOverride, User) {
  'use strict';

  /**
   * The SendEvent model module.
   * @module model/SendEvent
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SendEvent</code>.
   * @alias module:model/SendEvent
   * @class
   * @param event {String} 
   * @param user {module:model/User} 
   */
  var exports = function(event, user) {
    this.event = event;
    this.user = user;
  };

  /**
   * Constructs a <code>SendEvent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SendEvent} obj Optional instance to populate.
   * @return {module:model/SendEvent} The populated <code>SendEvent</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('event'))
        obj.event = ApiClient.convertToType(data['event'], 'String');
      if (data.hasOwnProperty('user'))
        obj.user = User.constructFromObject(data['user']);
      if (data.hasOwnProperty('data'))
        obj.data = Data.constructFromObject(data['data']);
      if (data.hasOwnProperty('scheduled_at'))
        obj.scheduledAt = ApiClient.convertToType(data['scheduled_at'], 'String');
      if (data.hasOwnProperty('override'))
        obj.override = EventOverride.constructFromObject(data['override']);
    }
    return obj;
  }

  /**
   * @member {String} event
   */
  exports.prototype.event = undefined;

  /**
   * @member {module:model/User} user
   */
  exports.prototype.user = undefined;

  /**
   * @member {module:model/Data} data
   */
  exports.prototype.data = undefined;

  /**
   * @member {String} scheduledAt
   */
  exports.prototype.scheduledAt = undefined;

  /**
   * @member {module:model/EventOverride} override
   */
  exports.prototype.override = undefined;


  return exports;

}));
