/*
 * Raven API
 * This is OpenAPI defintion for the APIs of Raven.  You can find out more about Raven at [https://ravenapp.dev/](https://ravenapp.dev/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@ravenapp.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

import { RavenApiClient } from "../RavenApiClient";

export class SendEventBulk {
  constructor(event, batch) {
    this.event = event;
    this.batch = batch;
  }

  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SendEventBulk();
      if (data.hasOwnProperty("event"))
        obj.event = RavenApiClient.convertToType(data["event"], "String");
      if (data.hasOwnProperty("batch"))
        obj.batch = RavenApiClient.convertToType(data["batch"], [Object]);
    }
    return obj;
  }

  getEvent() {
    return this.event;
  }

  setEvent(event) {
    this.event = event;
  }

  getBatch() {
    return this.batch;
  }

  setBatch(batch) {
    this.batch = batch;
  }
}

SendEventBulk.prototype.event = undefined;

SendEventBulk.prototype.batch = undefined;
