/*
 * Raven API
 * This is OpenAPI defintion for the APIs of Raven.  You can find out more about Raven at [https://ravenapp.dev/](https://ravenapp.dev/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@ravenapp.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

export class SlackProfile {
  constructor() {
  }

  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SlackProfile();
      if (data.hasOwnProperty('access_token'))
        obj.accessToken = ApiClient.convertToType(data['access_token'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('channel_id'))
        obj.channelId = ApiClient.convertToType(data['channel_id'], 'String');
    }
    return obj;
  }

  getAccessToken() {
    return this.accessToken;
  }

  setAccessToken(accessToken) {
    this.accessToken = accessToken;
  }

  getEmail() {
    return this.email;
  }

  setEmail(email) {
    this.email = email;
  }

  getChannelId() {
    return this.channelId;
  }

  setChannelId(channelId) {
    this.channelId = channelId;
  }

}

SlackProfile.prototype.accessToken = undefined;

SlackProfile.prototype.email = undefined;

SlackProfile.prototype.channelId = undefined;


