/*
 * Raven API
 * This is OpenAPI defintion for the APIs of Raven.  You can find out more about Raven at [https://ravenapp.dev/](https://ravenapp.dev/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@ravenapp.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

import { RavenApiClient } from "../RavenApiClient";
import { convertToType } from "../utils";
export class SmsOverride {
  constructor() {}

  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SmsOverride();
      if (data.hasOwnProperty("sender"))
        obj.sender = convertToType(data["sender"], "String");
      if (data.hasOwnProperty("scheduled_at"))
        obj.scheduledAt = convertToType(data["scheduled_at"], "String");
    }
    return obj;
  }

  getSender() {
    return this.sender;
  }

  setSender(sender) {
    this.sender = sender;
  }

  getScheduledAt() {
    return this.scheduledAt;
  }

  setScheduledAt(scheduledAt) {
    this.scheduledAt = scheduledAt;
  }
}

SmsOverride.prototype.sender = undefined;

SmsOverride.prototype.scheduledAt = undefined;
