/*
 * Raven API
 * This is OpenAPI defintion for the APIs of Raven.  You can find out more about Raven at [https://ravenapp.dev/](https://ravenapp.dev/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@ravenapp.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

import { RavenApiClient } from "../RavenApiClient";
import { convertToType } from "../utils";
export class SuccessResponse {
  constructor() {}

  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SuccessResponse();
      if (data.hasOwnProperty("success"))
        obj.success = convertToType(data["success"], "Boolean");
      if (data.hasOwnProperty("id"))
        obj.id = convertToType(data["id"], "String");
    }
    return obj;
  }

  getSuccess() {
    return this.success;
  }

  setSuccess(success) {
    this.success = success;
  }

  getId() {
    return this.id;
  }

  setId(id) {
    this.id = id;
  }
}

SuccessResponse.prototype.success = undefined;

SuccessResponse.prototype.id = undefined;
