/*
 * Raven API
 * This is OpenAPI defintion for the APIs of Raven.  You can find out more about Raven at [https://ravenapp.dev/](https://ravenapp.dev/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@ravenapp.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

export class User {
  constructor() {
  }

  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new User();
      if (data.hasOwnProperty('user_id'))
        obj.userId = ApiClient.convertToType(data['user_id'], 'String');
      if (data.hasOwnProperty('mobile'))
        obj.mobile = ApiClient.convertToType(data['mobile'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('whatsapp_mobile'))
        obj.whatsappMobile = ApiClient.convertToType(data['whatsapp_mobile'], 'String');
      if (data.hasOwnProperty('onesignal_external_id'))
        obj.onesignalExternalId = ApiClient.convertToType(data['onesignal_external_id'], 'String');
      if (data.hasOwnProperty('fcm_tokens'))
        obj.fcmTokens = ApiClient.convertToType(data['fcm_tokens'], ['String']);
      if (data.hasOwnProperty('ios_tokens'))
        obj.iosTokens = ApiClient.convertToType(data['ios_tokens'], ['String']);
      if (data.hasOwnProperty('fcm_topic'))
        obj.fcmTopic = ApiClient.convertToType(data['fcm_topic'], ['String']);
      if (data.hasOwnProperty('fcm_device_group'))
        obj.fcmDeviceGroup = ApiClient.convertToType(data['fcm_device_group'], ['String']);
      if (data.hasOwnProperty('slack'))
        obj.slack = ApiClient.convertToType(data['slack'], Object);
      if (data.hasOwnProperty('onesignal_player_ids'))
        obj.onesignalPlayerIds = ApiClient.convertToType(data['onesignal_player_ids'], ['String']);
    }
    return obj;
  }

  getUserId() {
    return this.userId;
  }

  setUserId(userId) {
    this.userId = userId;
  }

  getMobile() {
    return this.mobile;
  }

  setMobile(mobile) {
    this.mobile = mobile;
  }

  getEmail() {
    return this.email;
  }

  setEmail(email) {
    this.email = email;
  }

  getWhatsappMobile() {
    return this.whatsappMobile;
  }

  setWhatsappMobile(whatsappMobile) {
    this.whatsappMobile = whatsappMobile;
  }

  getOnesignalExternalId() {
    return this.onesignalExternalId;
  }

  setOnesignalExternalId(onesignalExternalId) {
    this.onesignalExternalId = onesignalExternalId;
  }

  getFcmTokens() {
    return this.fcmTokens;
  }

  setFcmTokens(fcmTokens) {
    this.fcmTokens = fcmTokens;
  }

  getIosTokens() {
    return this.iosTokens;
  }

  setIosTokens(iosTokens) {
    this.iosTokens = iosTokens;
  }

  getFcmTopic() {
    return this.fcmTopic;
  }

  setFcmTopic(fcmTopic) {
    this.fcmTopic = fcmTopic;
  }

  getFcmDeviceGroup() {
    return this.fcmDeviceGroup;
  }

  setFcmDeviceGroup(fcmDeviceGroup) {
    this.fcmDeviceGroup = fcmDeviceGroup;
  }

  getSlack() {
    return this.slack;
  }

  setSlack(slack) {
    this.slack = slack;
  }

  getOnesignalPlayerIds() {
    return this.onesignalPlayerIds;
  }

  setOnesignalPlayerIds(onesignalPlayerIds) {
    this.onesignalPlayerIds = onesignalPlayerIds;
  }

}

User.prototype.userId = undefined;

User.prototype.mobile = undefined;

User.prototype.email = undefined;

User.prototype.whatsappMobile = undefined;

User.prototype.onesignalExternalId = undefined;

User.prototype.fcmTokens = undefined;

User.prototype.iosTokens = undefined;

User.prototype.fcmTopic = undefined;

User.prototype.fcmDeviceGroup = undefined;

User.prototype.slack = undefined;

User.prototype.onesignalPlayerIds = undefined;


