/*
 * Raven API
 * This is OpenAPI defintion for the APIs of Raven.  You can find out more about Raven at [https://ravenapp.dev/](https://ravenapp.dev/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@ravenapp.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.RavenApi) {
      root.RavenApi = {};
    }
    root.RavenApi.User = factory(root.RavenApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The User model module.
   * @module model/User
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>User</code>.
   * @alias module:model/User
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/User} obj Optional instance to populate.
   * @return {module:model/User} The populated <code>User</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('user_id'))
        obj.userId = ApiClient.convertToType(data['user_id'], 'String');
      if (data.hasOwnProperty('mobile'))
        obj.mobile = ApiClient.convertToType(data['mobile'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('whatsapp_mobile'))
        obj.whatsappMobile = ApiClient.convertToType(data['whatsapp_mobile'], 'String');
      if (data.hasOwnProperty('onesignal_external_id'))
        obj.onesignalExternalId = ApiClient.convertToType(data['onesignal_external_id'], 'String');
      if (data.hasOwnProperty('fcm_tokens'))
        obj.fcmTokens = ApiClient.convertToType(data['fcm_tokens'], ['String']);
      if (data.hasOwnProperty('ios_tokens'))
        obj.iosTokens = ApiClient.convertToType(data['ios_tokens'], ['String']);
      if (data.hasOwnProperty('fcm_topic'))
        obj.fcmTopic = ApiClient.convertToType(data['fcm_topic'], ['String']);
      if (data.hasOwnProperty('fcm_device_group'))
        obj.fcmDeviceGroup = ApiClient.convertToType(data['fcm_device_group'], ['String']);
      if (data.hasOwnProperty('slack'))
        obj.slack = ApiClient.convertToType(data['slack'], Object);
      if (data.hasOwnProperty('onesignal_player_ids'))
        obj.onesignalPlayerIds = ApiClient.convertToType(data['onesignal_player_ids'], ['String']);
    }
    return obj;
  }

  /**
   * @member {String} userId
   */
  exports.prototype.userId = undefined;

  /**
   * @member {String} mobile
   */
  exports.prototype.mobile = undefined;

  /**
   * @member {String} email
   */
  exports.prototype.email = undefined;

  /**
   * @member {String} whatsappMobile
   */
  exports.prototype.whatsappMobile = undefined;

  /**
   * @member {String} onesignalExternalId
   */
  exports.prototype.onesignalExternalId = undefined;

  /**
   * @member {Array.<String>} fcmTokens
   */
  exports.prototype.fcmTokens = undefined;

  /**
   * @member {Array.<String>} iosTokens
   */
  exports.prototype.iosTokens = undefined;

  /**
   * @member {Array.<String>} fcmTopic
   */
  exports.prototype.fcmTopic = undefined;

  /**
   * @member {Array.<String>} fcmDeviceGroup
   */
  exports.prototype.fcmDeviceGroup = undefined;

  /**
   * @member {Object} slack
   */
  exports.prototype.slack = undefined;

  /**
   * @member {Array.<String>} onesignalPlayerIds
   */
  exports.prototype.onesignalPlayerIds = undefined;


  return exports;

}));
