/*
 * Raven API
 * This is OpenAPI defintion for the APIs of Raven.  You can find out more about Raven at [https://ravenapp.dev/](https://ravenapp.dev/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@ravenapp.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src//index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src//index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.raven);
  }
}(this, function(expect, raven) {
  'use strict';

  var instance;

  describe('', function() {
    describe('SuccessResponse', function() {
      beforeEach(function() {
        instance = new raven.SuccessResponse();
      });

      it('should create an instance of SuccessResponse', function() {
        // TODO: update the code to test SuccessResponse
        expect(instance).to.be.a(raven.SuccessResponse);
      });

      it('should have the property success (base name: "success")', function() {
        // TODO: update the code to test the property success
        expect(instance).to.have.property('success');
        // expect(instance.getSuccess()).to.be(expectedValueLiteral);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.getId()).to.be(expectedValueLiteral);
      });

    });
  });

}));
