/*
 * Raven API
 * This is OpenAPI defintion for the APIs of Raven.  You can find out more about Raven at [https://ravenapp.dev/](https://ravenapp.dev/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@ravenapp.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src//index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src//index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.raven);
  }
}(this, function(expect, raven) {
  'use strict';

  var instance;

  describe('', function() {
    describe('EmailOverride', function() {
      beforeEach(function() {
        instance = new raven.EmailOverride();
      });

      it('should create an instance of EmailOverride', function() {
        // TODO: update the code to test EmailOverride
        expect(instance).to.be.a(raven.EmailOverride);
      });

      it('should have the property from (base name: "from")', function() {
        // TODO: update the code to test the property from
        expect(instance).to.have.property('from');
        // expect(instance.getFrom()).to.be(expectedValueLiteral);
      });

      it('should have the property cc (base name: "cc")', function() {
        // TODO: update the code to test the property cc
        expect(instance).to.have.property('cc');
        // expect(instance.getCc()).to.be(expectedValueLiteral);
      });

      it('should have the property bcc (base name: "bcc")', function() {
        // TODO: update the code to test the property bcc
        expect(instance).to.have.property('bcc');
        // expect(instance.getBcc()).to.be(expectedValueLiteral);
      });

      it('should have the property attachments (base name: "attachments")', function() {
        // TODO: update the code to test the property attachments
        expect(instance).to.have.property('attachments');
        // expect(instance.getAttachments()).to.be(expectedValueLiteral);
      });

      it('should have the property scheduledAt (base name: "scheduled_at")', function() {
        // TODO: update the code to test the property scheduledAt
        expect(instance).to.have.property('scheduledAt');
        // expect(instance.getScheduledAt()).to.be(expectedValueLiteral);
      });

    });
  });

}));
