/*
 * Raven API
 * This is OpenAPI defintion for the APIs of Raven.  You can find out more about Raven at [https://ravenapp.dev/](https://ravenapp.dev/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@ravenapp.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RavenApi);
  }
}(this, function(expect, RavenApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ProviderOverride', function() {
      beforeEach(function() {
        instance = new RavenApi.ProviderOverride();
      });

      it('should create an instance of ProviderOverride', function() {
        // TODO: update the code to test ProviderOverride
        expect(instance).to.be.a(RavenApi.ProviderOverride);
      });

      it('should have the property payload (base name: "payload")', function() {
        // TODO: update the code to test the property payload
        expect(instance).to.have.property('payload');
        // expect(instance.payload).to.be(expectedValueLiteral);
      });

      it('should have the property formParams (base name: "form_params")', function() {
        // TODO: update the code to test the property formParams
        expect(instance).to.have.property('formParams');
        // expect(instance.formParams).to.be(expectedValueLiteral);
      });

      it('should have the property queryParams (base name: "query_params")', function() {
        // TODO: update the code to test the property queryParams
        expect(instance).to.have.property('queryParams');
        // expect(instance.queryParams).to.be(expectedValueLiteral);
      });

      it('should have the property config (base name: "config")', function() {
        // TODO: update the code to test the property config
        expect(instance).to.have.property('config');
        // expect(instance.config).to.be(expectedValueLiteral);
      });

    });
  });

}));
