/*
 * Raven API
 * This is OpenAPI defintion for the APIs of Raven.  You can find out more about Raven at [https://ravenapp.dev/](https://ravenapp.dev/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@ravenapp.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../../src//index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../../src//index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.raven);
  }
}(this, function(expect, raven) {
  'use strict';

  var instance;

  describe('', function() {
    describe('SendEventBulk', function() {
      beforeEach(function() {
        instance = new raven.SendEventBulk();
      });

      it('should create an instance of SendEventBulk', function() {
        // TODO: update the code to test SendEventBulk
        expect(instance).to.be.a(raven.SendEventBulk);
      });

      it('should have the property event (base name: "event")', function() {
        // TODO: update the code to test the property event
        expect(instance).to.have.property('event');
        // expect(instance.getEvent()).to.be(expectedValueLiteral);
      });

      it('should have the property batch (base name: "batch")', function() {
        // TODO: update the code to test the property batch
        expect(instance).to.have.property('batch');
        // expect(instance.getBatch()).to.be(expectedValueLiteral);
      });

    });
  });

}));
