/*
 * Raven API
 * This is OpenAPI defintion for the APIs of Raven.  You can find out more about Raven at [https://ravenapp.dev/](https://ravenapp.dev/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@ravenapp.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Attachments', 'model/Data', 'model/EmailOverride', 'model/EmailRecipient', 'model/ErrorResponse', 'model/EventOverride', 'model/Param', 'model/ProviderOverride', 'model/PushOverride', 'model/Response', 'model/SendEvent', 'model/SendEventBulk', 'model/SlackOverride', 'model/SlackProfile', 'model/SmsOverride', 'model/SuccessResponse', 'model/User', 'model/VoiceOverride', 'model/WebhookOverride', 'model/WhatsappOverride', 'api/EventApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Attachments'), require('./model/Data'), require('./model/EmailOverride'), require('./model/EmailRecipient'), require('./model/ErrorResponse'), require('./model/EventOverride'), require('./model/Param'), require('./model/ProviderOverride'), require('./model/PushOverride'), require('./model/Response'), require('./model/SendEvent'), require('./model/SendEventBulk'), require('./model/SlackOverride'), require('./model/SlackProfile'), require('./model/SmsOverride'), require('./model/SuccessResponse'), require('./model/User'), require('./model/VoiceOverride'), require('./model/WebhookOverride'), require('./model/WhatsappOverride'), require('./api/EventApi'));
  }
}(function(ApiClient, Attachments, Data, EmailOverride, EmailRecipient, ErrorResponse, EventOverride, Param, ProviderOverride, PushOverride, Response, SendEvent, SendEventBulk, SlackOverride, SlackProfile, SmsOverride, SuccessResponse, User, VoiceOverride, WebhookOverride, WhatsappOverride, EventApi) {
  'use strict';

  /**
   * This_is_OpenAPI_defintion_for_the_APIs_of_Raven___You_can_find_out_more_about_Raven_at__httpsravenapp_dev_httpsravenapp_dev_.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var RavenApi = require('index'); // See note below*.
   * var xxxSvc = new RavenApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new RavenApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new RavenApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new RavenApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Attachments model constructor.
     * @property {module:model/Attachments}
     */
    Attachments: Attachments,
    /**
     * The Data model constructor.
     * @property {module:model/Data}
     */
    Data: Data,
    /**
     * The EmailOverride model constructor.
     * @property {module:model/EmailOverride}
     */
    EmailOverride: EmailOverride,
    /**
     * The EmailRecipient model constructor.
     * @property {module:model/EmailRecipient}
     */
    EmailRecipient: EmailRecipient,
    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse: ErrorResponse,
    /**
     * The EventOverride model constructor.
     * @property {module:model/EventOverride}
     */
    EventOverride: EventOverride,
    /**
     * The Param model constructor.
     * @property {module:model/Param}
     */
    Param: Param,
    /**
     * The ProviderOverride model constructor.
     * @property {module:model/ProviderOverride}
     */
    ProviderOverride: ProviderOverride,
    /**
     * The PushOverride model constructor.
     * @property {module:model/PushOverride}
     */
    PushOverride: PushOverride,
    /**
     * The Response model constructor.
     * @property {module:model/Response}
     */
    Response: Response,
    /**
     * The SendEvent model constructor.
     * @property {module:model/SendEvent}
     */
    SendEvent: SendEvent,
    /**
     * The SendEventBulk model constructor.
     * @property {module:model/SendEventBulk}
     */
    SendEventBulk: SendEventBulk,
    /**
     * The SlackOverride model constructor.
     * @property {module:model/SlackOverride}
     */
    SlackOverride: SlackOverride,
    /**
     * The SlackProfile model constructor.
     * @property {module:model/SlackProfile}
     */
    SlackProfile: SlackProfile,
    /**
     * The SmsOverride model constructor.
     * @property {module:model/SmsOverride}
     */
    SmsOverride: SmsOverride,
    /**
     * The SuccessResponse model constructor.
     * @property {module:model/SuccessResponse}
     */
    SuccessResponse: SuccessResponse,
    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User: User,
    /**
     * The VoiceOverride model constructor.
     * @property {module:model/VoiceOverride}
     */
    VoiceOverride: VoiceOverride,
    /**
     * The WebhookOverride model constructor.
     * @property {module:model/WebhookOverride}
     */
    WebhookOverride: WebhookOverride,
    /**
     * The WhatsappOverride model constructor.
     * @property {module:model/WhatsappOverride}
     */
    WhatsappOverride: WhatsappOverride,
    /**
     * The EventApi service constructor.
     * @property {module:api/EventApi}
     */
    EventApi: EventApi
  };

  return exports;
}));
